---
title: "Notes: retreat 2024"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## BYS retreat 2025

- Session National SDGs:
    - Discussion comparsion to other studies, analysis from Matti and Chinese papers
    - List factors or mechanisms that can create the regimes
    - Hypothesize and test causes that distinguishes clusters: wealth, income, corruption
    
- Futures discussion
    - Mistra: case studies in Indonesia with Robert, mining with Exeter,
    - Writers: Maike, Emilie, Tom, Caro, Peter, Juan, Tong(?)


## Notes meeting 2025

- We re-visit the selection of variables and downloaded all SDGs data from the UN API
    - script `sdg_api.R`
- We ran again into issues of missing values, took us long to solve it but we did some progress
- Decision: to include SDGs `c("5", "6", "10", "13","14", "15")` so add water and climate



## Mechanisms & feedbacks session

1. Fairness and perceptions
2. Market concentration
3. Aspiration
    - conspicuous consumtpion
    - social norms
4. Cooperation
5. Environmental change
6. Environmental shocks

**Literature review workflow**

- map research: who, what, etc + key topics
- effects social inequality on environment

Problems:

- Levels, aggregation
- Measures
- direct vs indirect effects
- intertwinness
- positive feedbacks vs negative ones

Policy = P; Inequality = I; Enviornment = E

```{r}
library(DiagrammeR)
mermaid(
    "graph TB
    P --> I
    I --> E
    "
)

mermaid(
    "graph TB
    P <--> I
    I <--> E
    P <--> E
    "
)
```

Environmental justice: colonialims etc

Potential way of coding:


